### ISSUE TITLE
authorization: REDACTED since Sep 14 2016

### ISSUE THREAD

**Issue by lahirug** [googleads/googleads-java-lib#100]
I see its failing to connect to adwords since Sep 14th with the existing develop-token which I used before. I see following error,
```
2016-10-05 13:12:13,169 [main][c.g.a.a.a.lib.utils.report_download][WARN][undefined][ ] accept-encoding: [gzip]
authorization: REDACTED
user-agent: [fatline-metrics-loader (AwApi-Java, Common-Java/2.9.0, Java/1.8.0_45, maven)]
developertoken: REDACTED
clientcustomerid: [id]
skipreportheader: true
skipcolumnheader: true
skipreportsummary: true
includezeroimpressions: false

Parameters:
__rdxml: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><reportDefinition xmlns:ns2="https://adwords.google.com/api/adwords/cm/v201601"><ns2:selector><ns2:fields>CampaignId</ns2:fields><ns2:fields>CampaignName</ns2:fields><ns2:fields>AdGroupId</ns2:fields><ns2:fields>AdGroupName</ns2:fields><ns2:fields>Clicks</ns2:fields><ns2:fields>Impressions</ns2:fields><ns2:fields>Cost</ns2:fields><ns2:fields>AveragePosition</ns2:fields><ns2:fields>Conversions</ns2:fields><ns2:dateRange><ns2:min>20150401</ns2:min><ns2:max>20150401</ns2:max></ns2:dateRange></ns2:selector><ns2:reportName>Criteria performance report #1475698327541</ns2:reportName><ns2:reportType>ADGROUP_PERFORMANCE_REPORT</ns2:reportType><ns2:dateRangeType>CUSTOM_DATE</ns2:dateRangeType><ns2:downloadFormat>CSV</ns2:downloadFormat></reportDefinition>
 
2016-10-05 13:12:13,170 [main][c.g.a.a.a.lib.utils.report_download][WARN][undefined][ ] Response received with status code 400 and message: Bad Request
 
2016-10-05 13:12:13,202 [main][com.highfive.core.Core][ERROR][undefined][ ] Uncaught exception in thread Thread[main,5,main] 
com.google.api.ads.adwords.lib.utils.v201601.DetailedReportDownloadResponseException: 400
	at com.google.api.ads.adwords.lib.utils.v201601.ReportDownloader.handleResponse(ReportDownloader.java:106)
	at com.google.api.ads.adwords.lib.utils.v201601.ReportDownloader.downloadReport(ReportDownloader.java:81)
	at com.parlaylabs.fatline.metrics.tools.AdWordsLoader.load(AdWordsLoader.java:152)
	at com.parlaylabs.fatline.metrics.tools.AdWordsLoader.main(AdWordsLoader.java:93)
```

**Comment by jradcliff** [comment]
Hi,

The `REDACTED` entries are due to a [change we made a while back](https://github.com/googleads/googleads-java-lib/blob/master/ChangeLog#L137) to ensure that logs would not include sensitive information. That change only impacted logging, so it won't affect the actual requests sent to the AdWords API.

The error you're seeing is due to the fact that [v201601 was sunset](http://googleadsdeveloper.blogspot.com/2016/08/adwords-api-v201601-sunset-reminder.html), so that version is no longer available. Please migrate to v201605 or higher, since [v201603 is now scheduled to sunset at the end of the month](http://googleadsdeveloper.blogspot.com/2016/10/adwords-api-v201603-sunset-reminder.html).

If you'd like to receive emails for AdWords API blog posts (including sunset and release reminders), please join the [AdWords API Announcements group](https://groups.google.com/forum/#!forum/adwordsapi-announcements).

Thanks,
Josh, AdWords API Team

**Comment by lahirug** [comment]
@jradcliff I did and all good. Thanks for the response. Do you think proper error like you posted above would be helpful for older version users ?

**Comment by lahirug** [comment]
And we recently got a similar email from data-store saying that they are retiring older versions so as a user I was expecting a similar email so really didn't bother trying a newer version 😒 . We were running adwords api in GCE with some dataflow job, i think if you can streamline version update emailing thing for all the gcloud libraries that would be a great help.

**Comment by jradcliff** [comment]
Hi,

The deprecation schedule for each API varies significantly, and the AdWords API is a bit of a special case because the contact info is maintained in **AdWords API Center** instead of the [Cloud Console](https://cloud.google.com/console). Fortunately, for the AdWords API the deprecation schedule is pretty predictable -- please see our **Deprecation Schedule** page here:

https://developers.google.com/adwords/api/docs/sunset-dates

That being said, I understand that keeping track of deprecations can be challenging, especially if you're using multiple APIs. I'll pass your feedback on to the rest of the team.

Thanks,
Josh, AdWords API Team
