### ISSUE TITLE
Getting + Setting Campaign Ad Schedule 

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#111]
I am trying to figure out where to get the ad schedule from a Campaign. 
[com.google.api.ads.adwords.axis.v201702.cm.Campaign]

I found an example with JavaScript from the AdWords site in which the campaign knows about the ad schedule via targeting, see below URL 
[https://developers.google.com/adwords/scripts/docs/examples/ad-schedules](https://developers.google.com/adwords/scripts/docs/examples/ad-schedules)

How is getting and setting the Ad Schedule Implemented here with Java? I could not find any references to examples using an AdSchedule class. 

Thanks in advance!

**Comment by jradcliff** [comment]
Hi,

You can add AdSchedules to your campaign via the [CampaignCriterionService](https://developers.google.com/adwords/api/docs/reference/latest/CampaignCriterionService.AdSchedule). This will be very similar to the [AddCampaignTargetingCriteria example](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201702/targeting/AddCampaignTargetingCriteria.java), except you'll use `AdSchedule` criteria instead of `Location` and `LocationGroups` criteria.

Please check out that example and let me know if you have any questions.

Cheers,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

Since there haven't been any further comments or questions here, I'll close this one. Feel free to reopen if you're still having trouble.

Thanks,
Josh, AdWords API Team
