### ISSUE TITLE
Add Find ProductPartitionNode by Id Method

### ISSUE THREAD

**Issue by applecrusher** [googleads/googleads-java-lib#114]
I was quite surprised how difficult it was to find a node by product id. I had to manually transverse through all the children to find it. For future reference it might be a nice feature to add a findProductPartitionNodeById method. Something like what I did quickly below

```
	public ProductPartitionNode findProductNodeById(ProductPartitionNode root, Long id) {

		Iterable<ProductPartitionNode> children = root.getChildren();
		ProductPartitionNode returnValue = null;

		for (ProductPartitionNode child : children) {

			Iterable<ProductPartitionNode> newChildren = child.getChildren();
			int size = 0;
			for (ProductPartitionNode t : newChildren) {
				size++;
			}

			if (id.equals(child.getProductPartitionId())) {
				return child;
			}

			if (size > 0) {
				returnValue = findProductNodeById(child, id);
			}

			if (returnValue != null) {
				return returnValue;
			}

		}

		return returnValue;

	}
		
		return returnValue;
	
		
		
	} 
```

**Comment by jradcliff** [comment]
Hi,

Thanks for bringing up this suggestion. Could you provide more details on your use case and process so I can better understand the point at which you need to perform this lookup?

Cheers,
Josh Radcliff, AdWords API Team

**Comment by applecrusher** [comment]
What I needed to do is exclude an product partition node based on
partitionId. To my knowledge, there is no way I found to instantiate a
productPartitionNode just based on id, I had to transverse from the root.
Once I found it traversing the tree, then I was able to exclude it.

**Comment by jradcliff** [comment]
Hi,

Sorry for the delayed response. One issue with adding a lookup by ID is that if you have mutated the tree, then any new nodes will not have an ID. The `ProductPartitionTree` only assigns temporary IDs (in [`createAddOperations`](https://github.com/googleads/googleads-java-lib/blob/master/modules/adwords_axis/src/main/java/com/google/api/ads/adwords/axis/utils/v201705/shopping/ProductPartitionTreeImpl.java#L513)) when you call `getMutateOperations`.

For your use case, are you creating a `ProductPartitionTree` solely for the purpose of excluding one or more nodes for which you already have the IDs? If so, the `ProductPartitionTree` may not be the ideal choice. If you have a list of IDs you want to exclude you could instead:

1. Issue an `AdGroupCriterionService.get` request with a predicate on `Id IN [x,y,z]`.
2. Construct the `REMOVE` and `ADD` operations based on the response from step 1.
3. Issue an `AdGroupCriterionService.mutate` request, passing in the operations from step 2.

This would be more efficient than constructing a complete `ProductPartitionTree` for the ad group because [`ProductPartitionTree.createAdGroupTree`](https://github.com/googleads/googleads-java-lib/blob/master/modules/adwords_axis/src/main/java/com/google/api/ads/adwords/axis/utils/v201705/shopping/ProductPartitionTree.java#L80) will retrieve *all* product partitions in the ad group, whereas in the approach above  you'll only be retrieving the product partitions you need to prepare your `mutate` request.

If I'm off base in terms of your workflow, please provide more details so we can come up with a good solution here.

Thanks,
Josh Radcliff, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

I haven't heard back on the suggestions I posted a while back, so I'll close out this issue, but feel free to reopen it if you have additional questions or suggestions.

Cheers,
Josh, AdWords API Team
