### ISSUE TITLE
Strange behavior of RateExceededError.RATE_EXCEEDED

### ISSUE THREAD

**Issue by dimasho** [googleads/googleads-java-lib#121]
Hi,

I opened a thread in the AdWords group and they asked to post it here too (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/adwords-api/jlYlnR5BEaI)

Looks like in the new lib (3.5.0) RateExceededError.RATE_EXCEEDED exception is an instance of DetailedReportDownloadResponseException and not ApiException as before.

TTP Response Code: 400, Type: RateExceededError.RATE_EXCEEDED 
at com.google.api.ads.adwords.lib.utils.v201705.DetailedReportDownloadResponseException$Builder.build(DetailedReportDownloadResponseException.java:35) 
at com.google.api.ads.adwords.lib.utils.AdHocReportDownloadHelperImpl.handleResponse(AdHocReportDownloadHelperImpl.java:117) 
at com.google.api.ads.adwords.lib.utils.AdHocReportDownloadHelperImpl.downloadReport(AdHocReportDownloadHelperImpl.java:60) 
at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
at java.lang.reflect.Method.invoke(Unknown Source) 
at com.google.api.ads.common.lib.utils.AdsUtilityInvocationHandler.handleInvocation(AdsUtilityInvocationHandler.java:46) 
at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84) 
at com.sun.proxy.$Proxy33.downloadReport(Unknown Source) 
at com.google.api.ads.adwords.lib.utils.AdHocReportDownloadHelper.downloadReport(AdHocReportDownloadHelper.java:46) 
at com.google.api.ads.adwords.lib.utils.v201705.ReportDownloader.downloadReport(ReportDownloader.java:73)

**Comment by jradcliff** [comment]
Hi,

I saw on the forum post that you recently upgraded from 2.20.0 to 3.5.0. I just compared the source for reporting utilities between those versions, and I haven't found any related changes.

Are you 100% sure that in 2.20.0 you were getting a `RateExceededError` from **reporting** requests? I ask because [AdHocReportDownloadHelperImpl](https://github.com/googleads/googleads-java-lib/blob/master/modules/ads_lib/src/main/java/com/google/api/ads/adwords/lib/utils/AdHocReportDownloadHelperImpl.java#L107) has always only thrown one of the following exception types, none of which extend `ApiException` or `RateExceededError`:

* [ReportDownloadResponseException](https://github.com/googleads/googleads-java-lib/blob/master/modules/ads_lib/src/main/java/com/google/api/ads/adwords/lib/utils/ReportDownloadResponseException.java) - extends `java.lang.Exception`
* [DetailedReportDownloadResponseException](https://github.com/googleads/googleads-java-lib/blob/master/modules/ads_lib/src/main/java/com/google/api/ads/adwords/lib/utils/DetailedReportDownloadResponseException.java) - subclass of `ReportDownloadResponseException`
* MalformedURLException
* IOException
* AuthenticationException

In contrast, calls to **non-reporting** services such as `ReportDefinitionService`, `CampaignService`, etc., will throw `RateExceededError`.

Thanks,
Josh Radcliff, AdWords API Team

**Comment by chenzhuo914** [comment]
Josh is right. There shouldn't be such behavior change.

The RateExceededError just wraps underlying AdWords API exception that is not related to rate limiting or is not retriable.

For reporting downloading, it never (in any previous versions) throws ApiException (see the list of possible exceptions from Josh), so there's no way for RateExceededError to contain an ApiException.

On the other hand, for other services (such as CampaignService), they may throw ApiException, therefore the RateExceededError may contain an ApiException. I guess what you saw (RateExceededError with an internal ApiException) was from an AdWords API service call, instead of report downloading.

**Comment by dimasho** [comment]
Probably you're right, we have a common wrapper for all the API calls, both services and reporting. Apparently we catched this exception from some service call. Sorry about that.

This explanation raises another question - any reason not to throw ApiException in the report downloading as well? This kind of exception requires a special handling which on its side requires additional info like scope and recommended sleep duration.

Thanks

**Comment by chenzhuo914** [comment]
This is a question to the client library, and I'm sure Josh can share some insights.

On the RateLimiter side, yes it differentiates report downloading and services, and handles rate limits (scope, wait after seconds) of two categories separately.

**Comment by jradcliff** [comment]
Hi,

Having the report downloader throw ApiException is an interesting idea. It's a bit of a challenge for the following reasons.

## No WSDL for reporting

Unlike with the SOAP services such as `CampaignService`, we do not have a WSDL that indicates all possible exceptions that could appear in a failed reporting response.

## Where to introduce `ApiException`

Currently, the `downloadReport` method signature has

    throws ReportException, ReportDownloadResponseException

and the method throws exceptions as follows (note that I just updated my
previous comment, which was not 100% correct):

* `ReportException`
  * If the request fails due to an `IOException`, `MalformedURLException`, or `AuthenticationException`.
* `ReportDownloadResponseException`
  * If the HTTP status code `!= 200` and
  * Reading the input stream from the response fails with an `IOException`.
* `DetailedReportDownloadResponseException` -   This is the *only* case where the response will contain an `ApiException` and its fields.
  * If the HTTP status code `!= 200` and
  * Reading the input stream from the response succeeds.

Therefore, it makes sense to modify `DetailedReportDownloadResponseException` so that it
extends `ApiException` instead of `ReportDownloadResponseException`. The only problem with that
change is that it will be a breaking change for anyone who is explicitly catching
`ReportDownloadResponseException` in a try/catch block.

The above can all be addressed, but it'll take some time to iron out all the details. I'll update
this issue as I make progress.

Cheers,
Josh Radcliff, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

While reviewing open issues, I gave this one some more thought, and I recommend detecting rate limit errors using the approach employed by the [RateLimiter extension](https://github.com/googleads/googleads-java-lib/tree/master/extensions/adwords_rate_limiter), as shown in its [ApiReportingRetryStrategy](https://github.com/googleads/googleads-java-lib/blob/master/extensions/adwords_rate_limiter/src/main/java/com/google/api/ads/adwords/extension/ratelimiter/ApiReportingRetryStrategy.java#L90).

I mention this because upon further review, having `DetailedReportDownloadResponseException` extend `ApiException` looks like a non-starter. :frowning_face: 

The reporting classes in the library currently are *not* dependent on the SOAP toolkit (Axis or JAX-WS) or the toolkit-specific and API version-specific classes generated from WSDLs, such as:

*  [com.google.api.ads.adwords.axis.v201710.cm.ApiException](https://github.com/googleads/googleads-java-lib/blob/master/modules/adwords_axis/src/main/java/com/google/api/ads/adwords/axis/v201710/cm/ApiException.java)
*  [com.google.api.ads.adwords.jaxws.v201710.cm.ApiException](https://github.com/googleads/googleads-java-lib/blob/master/modules/adwords_appengine/src/main/java/com/google/api/ads/adwords/jaxws/v201710/cm/ApiException.java)

This is a good thing, as it means users who are only interested in running reports can simply depend on the `com.google.api-ads/ads-lib` module, and not worry about Axis or JAX-WS dependencies and modules.

If we make `DetailedReportDownloadResponseException` extend `ApiException`, we'll need a separate `DetailedReportDownloadResponseException` class for JAX-WS and Axis and every version of the AdWords API, which would mean separate `ReportDownloader` classes for JAX-WS and Axis and every version of the AdWords API. In addition, any reporting-only users would have to bring in JAX-WS or Axis dependencies. All of this would be a breaking change for all users of the library, unfortunately.

Given the above, I'm going to close this issue, but feel free to reopen it if you have additional questions or ideas on this topic.

Thanks,
Josh, AdWords API Team
