### ISSUE TITLE
java.lang.VerifyError:

### ISSUE THREAD

**Issue by Padmanabana** [googleads/googleads-java-lib#129]
java.lang.VerifyError: Cannot inherit from final class in XssfWorbook poi java tomcat 8 

kindly solvve problem

**Comment by jradcliff** [comment]
Hi,

Could you provide some more context for this error? Are you encountering this while using the library, using the [rate limiter extension](https://github.com/googleads/googleads-java-lib/tree/master/extensions/adwords_rate_limiter), etc.? I ask because I'm not aware of any POI dependencies in the library.

Thanks,
Josh, AdWords API Team

**Comment by jradcliff** [comment]
Hi,

I'll close this out since I haven't heard back in a while. Feel free to reopen and provide more info if you're still encountering issues.

Thanks,
Josh, AdWords API Team
