### ISSUE TITLE
RateLimiterException: Need to wait to long

### ISSUE THREAD

**Issue by SallyChen47** [googleads/googleads-java-lib#148]
Hi,

I am using the TargetingIdeaServiceInterface to get new keyword suggestions and TrafficEstimatorServiceInterface to do the traffic estimation, but I always encounter the Exception: 

com.google.api.ads.adwords.extension.ratelimiter.RateLimiterException: Need to wait too long (more than 30000 seconds).
	at com.google.api.ads.adwords.extension.ratelimiter.ApiServicesRetryStrategy.calcWaitTime(ApiServicesRetryStrategy.java:159)
	at com.google.api.ads.adwords.extension.ratelimiter.ApiServicesRetryStrategy.calcWaitTimeBeforeCall(ApiServicesRetryStrategy.java:103)
	at com.google.api.ads.adwords.extension.ratelimiter.ApiRetryHelper.callWithRetries(ApiRetryHelper.java:69)
	at com.google.api.ads.adwords.extension.ratelimiter.ApiRateLimiter.run(ApiRateLimiter.java:59)
	at com.google.api.ads.adwords.extension.ratelimiter.ApiInvocationHandlerWithRateLimiter.handleInvocation(ApiInvocationHandlerWithRateLimiter.java:45)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
	at com.sun.proxy.$Proxy27.get(Unknown Source)

I am using AdWordsServicesWithRateLimiter with the property settings:

 		System.setProperty(ApiServicesRetryStrategy.MAX_ATTEMPTS_ON_RATE_EXCEEDED_ERROR_PROPERTY, "3");
		System.setProperty(ApiServicesRetryStrategy.MAX_WAIT_TIME_ON_RATE_EXCEEDED_ERROR_PROPERTY, "30000");

When this error occurred, it wouldn't retry 3 times as my 'MAX_ATTEMPTS_ON_RATE_EXCEEDED_ERROR_PROPERTY' setting and exit immediately with that exception.

Sometimes, I will meet this error, 'ApiException{applicationExceptionType=ApiException, errors=[RateExceededError{apiErrorType=RateExceededError, errorString=RateExceededError.RATE_EXCEEDED, fieldPath=, rateName=RATE_LIMIT, rateScope=ACCOUNT, reason=RATE_EXCEEDED, retryAfterSeconds=30, trigger=}]}' and it will retry again, but not after 30 second as my setting. 

Best Regards,
Sally

**Comment by nwbirnie** [comment]
In the error you can see that the API is suggesting you wait 30 seconds prior to retrying this request (retryAfterSeconds=30). We multiply this value by a random number between 1 and 2 to determine the actual wait time. Therefore the max wait time for this particular exception will be 60 seconds. Hence, your setting of MAX_WAIT_TIME_ON_RATE_EXCEEDED_ERROR_PROPERTY = 30000 will never support this and you receive this error. The default value for this setting is 86400. Is there some reason that this wasn't suitable for your implementation? Otherwise, just running with the default setting should fix this error.

Additionally for context, you can see that you are encountering a rate limit on the number of operations per AdWords account. A common cause of this is if you have multiple threads processing an account in parallel, each performing a different operation, e.g. downloading 20 different report types for an account in parallel. A better strategy is to download one report for all accounts in parallel with each account assigned to a different thread. As a best practice keep your global number of AW API threads below 15 for the best performance. Batch processing may also be used to 1. handle retries, and 2. manage the load for large jobs. For more information please see this [guide](https://developers.google.com/adwords/api/docs/guides/bestpractices).

**Comment by SallyChen47** [comment]
Hi nwbirnie,

Thank you for your quick reply. I removed the MAX_WAIT_TIME_ON_RATE_EXCEEDED_ERROR_PROPERTY setting and kept the default setting, but I still got this error(com.google.api.ads.adwords.extension.ratelimiter.RateLimiterException: Need to wait too long (more than 86400 seconds)) and exit immediately without retry any reties.

BTW, I would like to use batch jobs, but unfortunately, BatchJobService doesn't support TargetindIdeaService.get operation and only supports these mutate operations(https://developers.google.com/adwords/api/docs/guides/batch-jobs#supported_operations). I make 5 requests using targetIdeaService to generate new keywords for 5 ad groups in parallel.  Any suggestion for me to avoid the RateLimiter Exception, since the target Idea API is different from other downloading report APIs. For TargetingIdeaService, it does not depend on my usage alone, but on the usage of all users on a certain time of the day, and other factors.

Best Regards,
Sally

**Comment by SallyChen47** [comment]
Hi nwbirnie,

Thank you for your quick reply. I removed the MAX_WAIT_TIME_ON_RATE_EXCEEDED_ERROR_PROPERTY setting and kept the default setting, but I still got this error(com.google.api.ads.adwords.extension.ratelimiter.RateLimiterException: Need to wait too long (more than 86400 seconds)) and exit immediately without any reties.

BTW, I would like to use batch jobs, but unfortunately, BatchJobService doesn't support TargetindIdeaService.get operation and only supports these mutate operations(https://developers.google.com/adwords/api/docs/guides/batch-jobs#supported_operations). I make 5 requests using targetIdeaService to generate new keywords for 5 ad groups in parallel. Any suggestion for me to avoid the RateLimiter Exception, since the target Idea API is different from other downloading report APIs. For TargetingIdeaService, it does not depend on my usage alone, but on the usage of all users on a certain time of the day, and other factors.

Best Regards,
Sally
