### ISSUE TITLE
Atomicity Bug in ApiServicesRetryStrategy.java

### ISSUE THREAD

**Issue by SallyChen47** [googleads/googleads-java-lib#149]
In [ApiServicesRetryStrategy.java](https://github.com/googleads/googleads-java-lib/blob/master/extensions/adwords_rate_limiter/src/main/java/com/google/api/ads/adwords/extension/ratelimiter/ApiServicesRetryStrategy.java), line 137-141 will trigger an atomicity bug.

![screenshot from 2018-07-23 18-09-07](https://user-images.githubusercontent.com/39474077/43070930-c24965ae-8ea3-11e8-85f2-17e170ffe580.png)

Assume that we have two threads t1 and t2 running with same `clientCustomerId`, now both t1 and t2 execute line 133 and get `newTime = 1532341102239` (2018-07-23). Then they both execute line 137 at the same time and get `oldTime = 0`.

So when they execute line 141 in order, for example: t1 first, then t1 will add delta `1532341102239` to this `clientCustomerId` and return. Next, t2 also will add delta `1532341102239` to this `clientCustomerId`, result in the `waitTime = 3064682204000` (2067-02-11).

This bug will trigger a RateLimiterException, which was already mentioned in issues #148.

Below is the exception. `RetryAfterSeconds = 30` but ratelimiter logged: Need to wait too long (`more than 86400 seconds`).
![screenshot from 2018-07-23 17-28-54](https://user-images.githubusercontent.com/39474077/43072137-a441bb8e-8ea7-11e8-9774-0f125f622cdc.png)

**Comment by nwbirnie** [comment]
Thanks for taking the time to investigate, I see the problem here. I'll roll out a change for this over the next week. In the meantime, you could replace the do...while block with the following:

   `accountWaitUntil.accumulateAndGet(clientCustomerId, newTime, Math::max);`

As per this screenshot: 
![screenshot from 2018-07-23 13-36-57](https://user-images.githubusercontent.com/410275/43076892-9d8a5924-8e7d-11e8-9888-a10249b12f22.png)

**Comment by nwbirnie** [comment]
Fixed in release 0.1.3.
