### ISSUE TITLE
Exception as java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Rakesh-Vishwanathula** [googleads/googleads-java-lib#151]
Hi Guys,
I'm trying to connect DFP API with Eclipse based application(Mulesoft) and getting following Exception. 
Root Exception stack trace:
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<init>(OfflineCredentials.java:89)
	at com.google.api.ads.common.lib.auth.OfflineCredentials$Api.<clinit>(OfflineCredentials.java:81)
	at com.dfp.util.RunAdExchangeReport.onCall(RunAdExchangeReport.java:63)

I don't understand what i'm missing in my pom set up. Here is the attachment of source code and pom. 
[Archive.zip](https://github.com/googleads/googleads-java-lib/files/2240412/Archive.zip)
 you please provide solution ASAP as it is critical project?? Thanks!

**Comment by AlexanderDahmen** [comment]
The `com.google.api.ads.common.lib.auth.OfflineCredentials` class (and nested `Api` class) are part of the `ads-lib-3.16.0` jar file.
Checking that class' bytecode, there is a call to `com/google/common/base/Preconditions:checkNotNull(java/lang/Object; java/lang/String; java/lang/Object;) java/lang/Object` - which matches the call made in the [Source Code](https://github.com/googleads/googleads-java-lib/blob/e1c9189957fc5e318c43731a337068c8c43ebf3e/modules/ads_lib/src/main/java/com/google/api/ads/common/lib/auth/OfflineCredentials.java#L89) - so it is not the same error I had in issue #150 , where the bytecode contains an errornous call.

Looking at the guava-20.0.jar file, the method is definitely available:
```java
public static <T extends Object> T checkNotNull(T t, @javax.annotation.Nullable String string, @javax.annotation.Nullable Object o) { ... }
```

Are you sure your **Guava** dependency is the correct version for your ads-lib depdendency?
Maybe check your Maven Graph if there are any conflicts leading to wrong library versions being loaded.

**Comment by nwbirnie** [comment]
Hey,

As Alex points out, it's quite likely that you have the wrong version of Guava on the classpath. Could you post the output of mvn dependency:tree please?

Best wishes,

Nick

**Comment by Rakesh-Vishwanathula** [comment]
Hi Guys,

Here is the attachment of output of mvn dependency:tree. Looking forward for solution and please let me know if you need anything from my side. Thanks!

Regards,
Rakesh

**Comment by nwbirnie** [comment]
Thanks Rakesh, unfortunately the email reply dropped the attachment. Would you kindly attach on the Github UI please?

Best wishes,

Nick

**Comment by Rakesh-Vishwanathula** [comment]
[maven.zip](https://github.com/googleads/googleads-java-lib/files/2246962/maven.zip)
Here is the attachment. Thanks!

**Comment by nwbirnie** [comment]
The reason for this is that you have a direct dependency on Guava 23.6-jre. However, ads-lib and adwords-axis require Guava 20.0. Can you downgrade the dependency perhaps?

**Comment by Rakesh-Vishwanathula** [comment]
Tried with guava 20.0 but still getting same error.

**Comment by Rakesh-Vishwanathula** [comment]
We are using ads-lib and dfp-axis but not adwords-axis. Will that make any difference with guava??

**Comment by nwbirnie** [comment]
>Tried with guava 20.0 but still getting same error.
Could you post the full error trace and output of `mvn dependency:tree` when using Guava 20.0 please.

>We are using ads-lib and dfp-axis but not adwords-axis. Will that make any difference with guava??

That's fine, there should be no difference, since the Guava dependency comes from ads-lib rather than the axis packages.

**Comment by Rakesh-Vishwanathula** [comment]
Here is the attachment of Java class, pom, Error with full stack trace, mvn dependency:tree. I'm using dfp-axis version=v201805
[Archive 2.zip](https://github.com/googleads/googleads-java-lib/files/2250110/Archive.2.zip)

**Comment by Rakesh-Vishwanathula** [comment]
[maven-X.zip](https://github.com/googleads/googleads-java-lib/files/2250541/maven-X.zip)
Here is the full mvn dependency:tree -X

**Comment by nwbirnie** [comment]
I was digging into this and came across [this document](https://docs.mulesoft.com/mule-user-guide/v/3.8/classloader-control-in-mule) about classloaders in Mule. In short, Mule has a special classloader for its runtime which is likely to include Guava 18.0, you could verify this by checking the application folder for the offending jar. Since Java will by default try the parent classloader before loading a new class ([details](https://docs.oracle.com/cd/E19501-01/819-3659/beadf/index.html)) your application's dependency on Guava 20.0 is likely being ignored.

So there's a couple of options here in terms of a workaround.

1. rebuild the client libraries from source, swapping out the Guava 20.0 dependency with 18.0 and fixing the compiler errors (I just tried this and there's only two lines which need to be changed.)
2. swap out the mule installed Guava jar with 20.0 and check if Mule still runs

Would you be able to try one of these out and see if it solves your issue? 

Also, just in passing, is this a brand new application or was this working with a previous version of the client libs?

**Comment by Rakesh-Vishwanathula** [comment]
Finally it's working. Thanks!
