### ISSUE TITLE
UniversalAppCampaignSetting   OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE

### ISSUE THREAD

**Issue by st4rlight** [googleads/googleads-java-lib#195]
I'm using the API to create my app campaign, follow the documentation `https://developers.google.com/adwords/api/docs/guides/mobile-app-campaigns` step by step

but when I try to set `UniversalAppCampaignSetting`, I always get the error_msg
> OperationAccessDenied.OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE @ operations[0].operand.settings

And then I download the official example
`https://github.com/googleads/googleads-java-lib/blob/7647e0abef86e6bc85c9dbb950092a08ead0c1b3/examples/adwords_axis/src/main/java/adwords/axis/v201809/advancedoperations/AddUniversalAppCampaign.java`

change the campaignName and appId to my app
it still get the same error_msg

I'm sure that I have set the the channelSubType by
```java
campaign.setAdvertisingChannelSubType(AdvertisingChannelSubType.UNIVERSAL_APP_CAMPAIGN);
```

and without setting `UniversalAppCampaignSetting`, I can created my campaign successfully.

**Comment by nwbirnie** [comment]
Hi, thanks for reaching out. It looks like you're asking about how the App Campaigns API works, rather than the Java client library. I would suggest reaching out on the [AdWords API forum](https://groups.google.com/forum/#!forum/adwordsapi-announcements), where our support team will be happy to advise on the proper usage and can investigate potential bugs.
