### ISSUE TITLE
Problem while creating custom audience

### ISSUE THREAD

**Issue by Sangita865** [googleads/googleads-java-lib#204]
I am created Google Ads Test Account. Inside the Google Ads Test Account, I have created subaccount(A1).
All campaigns are  created/launched using sub-accounts successfully
When we try to create custom list through this sub-account, we immediately get the same error, "Your account is currently not eligible for customer match"

But I have observed one strange thing, if I try to create custom audience with the main account. I am able to create it and able to upload the custom audience there, but doesn't have facility to create campaign over the main account, so subaccount is needed to create campaign.

When I create campaign in the subaccount(962-806-0115) shown in the image, custom audience of the main account(398-184-6043) is not visible in the custom audience dropdown of the campaign, so it seems we need to create custom audience with the subaccount  then only it would be visible during creation of the campaign.

Kindly suggest something how we can create the custom audience.

We are facing the same problem with production account

Test Account (https://user-images.githubusercontent.com/71839937/94173121-0c76cc00-feb1-11ea-8222-0cd48f3304ee.png)
Production account(https://user-images.githubusercontent.com/71839937/94173898-2d8bec80-feb2-11ea-9432-74c7ad5d7530.png)
)

**Comment by nwbirnie** [comment]
Customer match is only eligible to run in accounts which meet the [policy](https://support.google.com/adspolicy/answer/6299717?hl=en-GB). I believe that this means you cannot create a customer match user list in the manager account and use it for targeting in a subaccount which is not eligible. I would suggest verifying this by reaching out on the [AdWords API forum](https://groups.google.com/g/adwords-api/). I also think that this means CM is not available for test accounts, since by definition they have $0 spend.

**Comment by nwbirnie** [comment]
Closing since this isn't directly related to the Java client library for AW API.
