### ISSUE TITLE
GetCampaigns service not returning any response

### ISSUE THREAD

**Issue by letscodewithrajat** [googleads/googleads-java-lib#215]
Hi Team,

I am trying to run GetCampaigns.java to get the campaign details from my test account but there is no response or error on console. I updated the ads.properties file with the details which were generated after executing AuthenticateInDesktopApplication.java. 
I need assistance with debugging this issue. Thanks in advance.

"SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
"

Thanks
Rajat

**Comment by jradcliff** [comment]
Hi Rajat,

If you're new to the API, please use the new [Google Ads API](https://developers.google.com/google-ads/api/docs/start) instead, and its accompanying library, [google-ads-java](https://github.com/googleads/google-ads-java).

The logging warning you're seeing is due to you not having an SLF4J bridge jar on your classpath. You can see how the examples configure the logging classpath and SLF4J in the [examples pom.xml](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/pom.xml#L139).

Even without logging configured, however, you should still be seeing the messages printed to `System.out` or `System.err` from the example. I suggest trying to step through the example in a debugger in your IDE to see where the process gets stuck, and we can go from there.

Thanks,
Josh, Google Ads API Team

**Comment by letscodewithrajat** [comment]
Hi Josh,

Thanks for the suggestion. I am using google ads API only. I added the SLF4J dependencies in my pom.xml but still getting warning message in the console. I have executed the code in the debug mode in IDE but couldn't find a place where it gets stuck. 

![image](https://user-images.githubusercontent.com/27491687/104402916-6218d680-557d-11eb-91dd-6a132f9e7c86.png)

Here is the dependency section in pom.xml

![image](https://user-images.githubusercontent.com/27491687/104403316-4a8e1d80-557e-11eb-92ad-2b42699dd8eb.png)

We have one more query on this.

![image (2)](https://user-images.githubusercontent.com/27491687/104403160-ebc8a400-557d-11eb-8806-5ab7962e0a67.png)

This is what we got from our client to do development work on.
Is there anything we are missing we needed to get created after test manager account?
Do we have to create Campaigns, if Yes where?
Use Case - we are only work with custom Audience List - Adding audiences from Client(3rd Party Platform to Google Ads)

Thanks
Rajat

**Comment by jradcliff** [comment]
Hi Rajat,

The `GetCampaigns` example will only return data if the account you run it against contains campaigns. You can create campaigns in your test account using the UI or [AddCampaigns.java](https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/src/main/java/com/google/ads/googleads/examples/basicoperations/AddCampaigns.java) if you'd like.

If you have further questions about the API that aren't specific to the client library, please reach out on our forum at https://groups.google.com/g/adwords-api.

Thanks,
Josh

**Comment by letscodewithrajat** [comment]
Hi Josh,

Thanks for getting back with this information. I tried few things as listed below.

1. Created a campaign from UI.

![image](https://user-images.githubusercontent.com/27491687/104551663-53a1ec00-565d-11eb-92f8-59f1d543c44f.png)

2. Executed AddCampaigns.java
3. Executed GetCampaigns.java

The AddCampaigns.java did not add a new campaign in my account and GetCampaign.java did not result any response.
Can you please suggest further. Thanks in advcance.

Thanks
Rajat

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced by the Google Ads API. Closing as stale.
