### ISSUE TITLE
ReachReport `COLUMNS_NOT_SUPPORTED` Not Supported 

### ISSUE THREAD

**Issue by MallikarjunHt** [googleads/googleads-java-lib#217]
I am getting this error few days back i got the report downloded and today it's not working.[ReportError.COLUMNS_NOT_SUPPORTED_FOR_REQUESTED_DIMENSIONS @ columns; trigger:'UNIQUE_REACH']

Thanks in advance
🤓

**Comment by christopherseeley** [comment]
This issue isn't specific to the Java client library -can you reach out on the [API forum](https://groups.google.com/g/google-doubleclick-for-publishers-api) instead? Including SOAP logs there would be helpful.

Generally this happens when you try to run a report that isn't supported - I typically recommend creating the a valid report in the UI and then recreating it in the API.
