### ISSUE TITLE
TemplateAd : adAsImage null with utility

### ISSUE THREAD

**Issue by davidbotella** [googleads/googleads-java-lib#37]
Hi,

Looks like the ExtendedAdGroup.getAds() method doesn't provide the adAsImage value (null) for TemplateAd ad type.

- DB.

**Comment by jradcliff** [comment]
Thanks for raising this. We'll look at it in conjunction with the other issue you raised on the utility.

**Comment by jradcliff** [comment]
Upon further investigation, this looks to be an issue with the AdWords API itself. The latest version of the library includes all of the `Image` selector fields, but the `adAsImage` attribute is still not in the response. I'll follow up with the ads team and update this issue when I have more information.

**Comment by jradcliff** [comment]
As it turns out, the `adAsImage` field is only relevant for `ADD` operations that create ads for template IDs [432](https://developers.google.com/adwords/api/docs/appendix/templateads#image_ctd_ad) and [455](https://developers.google.com/adwords/api/docs/appendix/templateads#image_cto_ad). It is *not* meant to be returned in `get` responses.

The documentation for [TemplateAd.adAsImage](https://developers.google.com/adwords/api/docs/reference/v201509/AdGroupAdService.TemplateAd#adAsImage) will be updated soon to clarify this. Since there are no remaining client library issues related to this, I'm going to close this issue.
