### ISSUE TITLE
ThreadLocal not closed

### ISSUE THREAD

**Issue by davidbotella** [googleads/googleads-java-lib#38]
Hi,

When using the library within a Glassfish web application, I get some warning (grave). Is this something that should be handled by the library (should not stay open) or from the library (AdwordsSession.close() or something like this) ?

Grave:   The web application [/AdWordsReportsWeb] created a ThreadLocal with key of type [com.google.api.client.util.escape.Platform$1] (value [com.google.api.client.util.escape.Platform$1@1f168378]) and a value of type [char[]] (value [[C@7f114b39]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Grave:   The web application [/AdWordsReportsWeb] created a ThreadLocal with key of type [org.apache.axis.utils.XMLUtils.ThreadLocalDocumentBuilder] (value [org.apache.axis.utils.XMLUtils$ThreadLocalDocumentBuilder@7bf193f7]) and a value of type [com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl] (value [com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl@31297cb3]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Grave:   The web application [/AdWordsReportsWeb] created a ThreadLocal with key of type [com.google.inject.internal.InjectorImpl$1] (value [com.google.inject.internal.InjectorImpl$1@1ab9e4fc]) and a value of type [java.lang.Object[]] (value [[Ljava.lang.Object;@22686a19]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Cheers,

David

**Comment by jradcliff** [comment]
The Guice injectors we create in the library are stored in static final variables, e.g., in [AdWordsServices](https://github.com/googleads/googleads-java-lib/blob/46eb2fff866c5cdac55f54502007c4583fb49978/modules/adwords_axis/src/main/java/com/google/api/ads/adwords/axis/factory/AdWordsServices.java#L46).

At the moment, we don't have any lifecycle hooks for destroying these singletons, and I hesitate to add them since we'll lose the thread safety associated with static final fields.

Do you have any further info from your container's documentation regarding why these are being flagged?

**Comment by jradcliff** [comment]
Closing this since I have not heard back on my question back in March. Please reopen (and provide the requested info) if this is still an issue.
