### ISSUE TITLE
 faultString: Version v201406 does not exist

### ISSUE THREAD

**Issue by saidsalem** [googleads/googleads-java-lib#44]
Hi,

I wrote a script to use for monthly reporting. I didn't change anything in my code and now I'm getting:
 faultString: Version v201406 does not exist

How can I fix this ?

**Comment by jradcliff** [comment]
Hi,

The latest version of the library does not include v201406 because that version was [sunset on 6 April 2015](https://developers.google.com/adwords/api/docs/sunset-dates).

To keep up to date with sunsets and other important announcements, I recommend following [our blog](http://googleadsdeveloper.blogspot.com/search/label/adwords_api).

Thanks,
Josh, AdWords API Team
