### ISSUE TITLE
Missing VIDEO_PERFORMANCE_REPORT in ReportDefinitionReportType

### ISSUE THREAD

**Issue by lpereirafernandez** [googleads/googleads-java-lib#52]
Looks like the value VIDEO_PERFORMANCE_REPORT is missing in the com.google.api.ads.adwords.lib.jaxb.v201509.ReportDefinitionReportType as we are getting java.lang.IllegalArgumentException: No enum constant com.google.api.ads.adwords.lib.jaxb.v201509.ReportDefinitionReportType.VIDEO_PERFORMANCE_REPORT when trying to use the new report

**Comment by jradcliff** [comment]
Thanks for pointing that out, and sorry I missed this! I'll get this fixed in an upcoming patch.

**Comment by jradcliff** [comment]
In the meantime, one workaround would be to use an `AWQL` request for `VIDEO_PERFORMANCE_REPORT`, since that does not rely on the jaxb enums. Check out the [DownloadCriteriaReportWithAwql example](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201509/reporting/DownloadCriteriaReportWithAwql.java) for reference.

**Comment by jradcliff** [comment]
Fixed in release [2.6.0](https://github.com/googleads/googleads-java-lib/releases/tag/2.6.0). Please see the updated [ReportDefinitionReportType enums](https://github.com/googleads/googleads-java-lib/blob/master/modules/ads_lib/src/main/java/com/google/api/ads/adwords/lib/jaxb/v201509/ReportDefinitionReportType.java#L118).

**Comment by barak066** [comment]
where can i find the api for VIDEO_PERFORMANCE_REPORT  in java ?

**Comment by jradcliff** [comment]
The `enum` instance is defined in [ReportDefinitionReportType](https://github.com/googleads/googleads-java-lib/blob/master/modules/ads_lib/src/main/java/com/google/api/ads/adwords/lib/jaxb/v201509/ReportDefinitionReportType.java#L118).

To see the list of fields available for that report, please refer to the documentation here:

https://developers.google.com/adwords/api/docs/appendix/reports/video-performance-report
