### ISSUE TITLE
client buffers entire result before returning InputStream

### ISSUE THREAD

**Issue by ilyastam** [googleads/googleads-java-lib#57]
I have the following code:
```
ReportDownloader reportDownloader = new ReportDownloader(session);
ReportDownloadResponse response = reportDownloader.downloadReport(reportDefinition); //configures to fetch a CSV report 
response.getInputStream();
```
 `reportDownloader.downloadReport(reportDefinition);` blocks until all data is received. 

There should be a way to stream CSV without buffering.

**Comment by jradcliff** [comment]
On a successful request, the ReportDownloader does not explicitly consume the entire InputStream before returning.

    private ReportDownloadResponse handleResponse(RawReportDownloadResponse response)
        throws ReportDownloadResponseException {
      if (response.getHttpStatus() == HttpURLConnection.HTTP_OK) {
        return new ReportDownloadResponse(response);
      }

I would expect this to behave as described in the [Report Downloader page](https://github.com/googleads/googleads-java-lib/wiki/ReportDownloader-utilities#process-the-report-contents-as-a-stream).

Are you saying that `response.getInputStream()` blocks? If so, I'll take a look at the underlying HTTP library we're using to see if it's consuming the stream before returning.

**Comment by ilyastam** [comment]
Yes, I was able to see this in the debugger, and also by profiling the code with log statements.

**Comment by jradcliff** [comment]
I just stepped through several report executions, and I did not see the entire contents being buffered before the `response.getInputStream` returned.

I'm constructing a reader as follows:

    reader = new BufferedReader(new InputStreamReader(response.getInputStream()));

Then processing lines via:

    String line;
    while ((line = reader.readLine()) != null) {
        // Do something with the line
    }

The report contents I'm downloading contain `9,2336,428` bytes. Logging free memory during this process, I get the following:

Step|FreeMemoryInBytes|ChangeInFreeMemory
----|-----------------|------------------
Before downloadReport|407698200|0
After downloadReport|404888800|-2809400
After processing line 200000|492757760|87868960
After processing line 400000|457332136|-35425624
After processing line 600000|421908872|-35423264
After processing line 800000|386473464|-35435408
After processing line 1000000|488590768|102117304
After processing line 1200000|452907920|-35682848
After processing line 1400000|417184760|-35723160
After processing line 1600000|381495224|-35689536
After processing line 1800000|488877704|107382480
After processing line 2000000|452908296|-35969408
Completed|422465208|-30443088

As you can see, the process never consumes `9,2336,428` bytes of memory (and even garbage collects over 83 MB of memory after processing the first 200,000 lines), which strongly suggests that the entire contents are not being read.

In addition, I'm logging every 200,000 lines, and there are significant pauses between those steps. This further suggests that the contents are being read in chunks.

You said your were able to see this in the debugger. Could you provide more details?

Thanks

**Comment by ilyastam** [comment]
I have instrumented my code with some logging as follows:
```
    long start = System.currentTimeMillis();
    ReportDownloadResponse response = reportDownloader.downloadReport(reportDefinition);
    LOG.info("Took {} sec to download report", (double)(System.currentTimeMillis() - start)/1000);
```
this logs out the following message:
```
Took 177.751 sec to download report
```
Furthermore, I have monitored memory usage by the process. Before the call to downloadReport(...) it was 316563200 and after - 472872768, yielding the difference of 156309568 bytes, which is roughly the size of the report I am downloading.

Lastly, when I run my program in the debugger, I can visually see it block for minutes when `reportDownloader.downloadReport(reportDefinition)` is executed.

Could you please show how your ReportDownloader is configured?

**Comment by jradcliff** [comment]
I don't have any specific configuration options for the `ReportDownloader`, but one thing to keep in mind is that the 177.751 seconds you're seeing is most likely due to the fact that it takes that long for the server to return *any* result for your specific reporting request. The reporting service will block until it has completed your request on the backend, then return a result. If that result is chunked, then you'll get the report contents in chunks as you consume the input stream.

One thing you might try is calling `System.gc()` immediately after `downloadReport` returns, and seeing if a bunch of memory is freed up. Even after that call, you should be able to consume the contents of the input stream.

**Comment by jradcliff** [comment]
I found a report request that generated over 300 MB of output and ran two sets of tests where I recorded the memory allocated and free memory using the following [borrowed from StackOverflow](http://stackoverflow.com/questions/74674/how-to-do-i-check-cpu-and-memory-usage-in-java):

```
  private static String getMemory() {
    Runtime runtime = Runtime.getRuntime();

    long maxMemory = runtime.maxMemory();
    long allocatedMemory = runtime.totalMemory();
    long freeMemory = runtime.freeMemory();

    long freeMem = freeMemory / 1024;
    long allocatedMem = allocatedMemory / 1024;
    long maxMem = maxMemory / 1024;
    long totalFreeMem = (freeMemory + (maxMemory - allocatedMemory)) / 1024;
    return 
        Joiner.on(',').join(new Long[]{freeMem, allocatedMem, maxMem, totalFreeMem});
  }
```

Note that the call to `ReportDownloader.downloadReport` took over a minute to return in both cases because it was waiting for the HTTP request to return.

## 1. Using getInputStream
Used `ReportDownloadResponse.getInputStream()` to consume the results, logging the memory usage at the start, after `ReportDownloadResponse.downloadReport` returned, and then after consuming every 500 lines of the report contents from the stream.

```
      BufferedReader responseReader = null;
      try {
        responseReader =
            new BufferedReader(new InputStreamReader(
                response.getInputStream()));
        int logIncrement = 500;
        int lines = 0;
        while (responseReader.readLine() != null) {
          if (lines % logIncrement == 0) {
            System.out.printf("Line %d,%s%n", lines, getMemory());
          }
          lines++;
        }
        System.out.printf("Final %d,%s%n", lines, getMemory());
      } finally {
        if (responseReader != null) {
          responseReader.close();
        }
      }
```

## 2. Using getAsString
Used `ReportDownloadResponse.getAsString()` to consume the results, logging the memory usage at the start, after `ReportDownloadResponse.downloadReport` returned, and after calling `getAsString()`.

```
      String reportContents = response.getAsString();
      if (reportContents == null) {
        throw new NullPointerException("Null contents");
      }
      System.out.printf("After getAsString %d,%s%n", reportContents.length(), getMemory());
```

The results strongly suggest that `downloadReport` is *not* downloading the entire report in memory in the first case.

## 1. Graphs for getInputStream:

Memory consumption up to the point of reading the first 500 lines of the report contents:

![report_stream_initial](https://cloud.githubusercontent.com/assets/6033175/11725002/4179ed22-9f45-11e5-8e2e-2e1d5613e609.png)

Memory consumption for the entire process, where all report contents were read from the stream (but not held in memory by my example):

![report_stream_all](https://cloud.githubusercontent.com/assets/6033175/11725022/6feedcbc-9f45-11e5-8aa4-17d4d8c98d02.png)

The jumps in the *free* memory clearly show that the JVM is able to free up around 100 MB of memory periodically as the example streams through the results.

In addition, at those jumps, we have:

    free       = ~484 MB
    allocated  = ~497 MB
    difference =  ~13 MB

The entire contents of the report cannot be in memory here, since the contents are over 300 MB.

## 2. Graphs for getAsString

Memory consumption for the entire process. There are far fewer steps here, of course, since I simply retrieve the contents as a String.

![report_getasstring_all](https://cloud.githubusercontent.com/assets/6033175/11725042/8a2cb356-9f45-11e5-9e10-8e9f25e74553.png)

Here, the JVM clearly allocated far more memory because it had to hold the entire contents of the report in memory.

## Conclusion

Given the above findings, I'm going to close this issue, but please reopen if you have additional questions or disagree with my analysis.

Thanks
