### ISSUE TITLE
Add a copy constructor for AdWordsSession class

### ISSUE THREAD

**Issue by chenzhuo914** [googleads/googleads-java-lib#58]
Use case: to download reports for ALL accounts under the top manager account, we do:
1. Create an AdWordsSession object from top manager account
2. For each AdWords account, spawn a thread
3. In the thread clone the AdWordsSession object, call setClientCustomerId() with that AdWords account ID.
4. Use this AdWordsSession to invoke relevant API

We need a copy constructor in step 3. Our copy implementation cannot guarantee thread safety (in theory).

**Comment by jradcliff** [comment]
A copy constructor may prove useful for other use cases, so I'll look into adding that.

Note, however, that a copy constructor alone would not guarantee thread safety. Since `AdWordsSession` is itself not thread-safe, there's no guarantee that another thread couldn't come in and modify the `AdWordsSession` you are copying *from* in the constructor, midway through the constructor's execution.

To address this, we may be able to create an `ImmutableAdWordsSession`. I'll look into that.

**Comment by jradcliff** [comment]
Fixed in [release 2.11.0](https://github.com/googleads/googleads-java-lib/releases/tag/2.11.0). See the new [ImmutableAdWordsSession](https://github.com/googleads/googleads-java-lib/blob/master/modules/ads_lib/src/main/java/com/google/api/ads/adwords/lib/client/AdWordsSession.java#L233) and associated [buildImmutable method](https://github.com/googleads/googleads-java-lib/blob/master/modules/ads_lib/src/main/java/com/google/api/ads/adwords/lib/client/AdWordsSession.java#L472).
