### ISSUE TITLE
GetRefreshToken

### ISSUE THREAD

**Issue by vivekimsit** [googleads/googleads-java-lib#64]
It seems a silly question but AFAIK to generate refresh token I need to client the client utility [GetRefreshToken](https://github.com/googleads/googleads-java-lib/blob/master/examples/dfp_axis/src/main/java/dfp/axis/auth/GetRefreshToken.java) for every user which involves copy pasting input from browser which I think can't be automates easily. What I am missing?

**Comment by jradcliff** [comment]
The `GetRefreshToken` examples assume that you have an [Installed application](https://developers.google.com/identity/protocols/OAuth2#installed). The use case you described sounds like a good fit for a **Web server application**, which is documented at the following links:

- [Flow diagram/overview](https://developers.google.com/identity/protocols/OAuth2#webserver)
- [Details](https://developers.google.com/identity/protocols/OAuth2WebServer)

To use that flow with the Java client library, you should set up a handler for the [redirect_uri](https://developers.google.com/identity/protocols/OAuth2WebServer#redirecting) you registered with your Web server application at https://console.developers.google.com. The handler will be similar to `GetRefreshToken`, only you should modify the `CALLBACK_URL` in [GetRefreshToken.java](https://github.com/googleads/googleads-java-lib/blob/master/examples/dfp_axis/src/main/java/dfp/axis/auth/GetRefreshToken.java#L59) so that it instead points to your registered `redirect_uri`.

Note that in order to get a **refresh** token in addition to the **access token** from that final step, you'll need to request [offline access](https://developers.google.com/identity/protocols/OAuth2WebServer#offline) by including `access_type=offline` when you redirect the user to the Google OAuth endpoint `https://accounts.google.com/o/oauth2/v2/auth` in the [first step of the OAuth flow](https://developers.google.com/identity/protocols/OAuth2WebServer#redirecting).

I'll close this issue, but if anything is unclear feel free to reopen it and add further comments.

Thanks,
Josh, AdWords API Team
